In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\jayal\Desktop\attribution_data.csv")

In [3]:
df.head()

,cookie,time,interaction,conversion,conversion_value,channel
0,00000FkCnDfDDf0iC97iC703B,2018-07-03T13:02:11Z,impression,0,0.0,Instagram
1,00000FkCnDfDDf0iC97iC703B,2018-07-17T19:15:07Z,impression,0,0.0,Online Display
2,00000FkCnDfDDf0iC97iC703B,2018-07-24T15:51:46Z,impression,0,0.0,Online Display
3,00000FkCnDfDDf0iC97iC703B,2018-07-29T07:44:51Z,impression,0,0.0,Online Display
4,0000nACkD9nFkBBDECD3ki00E,2018-07-03T09:44:57Z,impression,0,0.0,Paid Search

In [4]:
df.shape

(586737, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 586737 entries, 0 to 586736
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cookie            586737 non-null  object
 1   time              586737 non-null  object
 2   interaction       586737 non-null  object
 3   conversion        586737 non-null  int64
 4   conversion_value  586737 non-null  float64
 5   channel           586737 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 26.9+ MB

In [6]:
df.describe()

          conversion  conversion_value
count  586737.000000     586737.000000
mean        0.030063          0.187871
std         0.170760          1.084498
min         0.000000          0.000000
25%         0.000000          0.000000
50%         0.000000          0.000000
75%         0.000000          0.000000
max         1.000000          8.500000

In [7]:
df.isnull().sum()

cookie              0
time                0
interaction         0
conversion          0
conversion_value    0
channel             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(4145)

In [11]:
print("Before removing duplicates:",df.shape)
df = df.drop_duplicates()
print("After removing duplicates:",df.shape)

Before removing duplicates: (582592, 6)
After removing duplicates: (582592, 6)

In [12]:
df['time'] = pd.to_datetime(df['time'],utc=True)

In [13]:
df['time'].dtype

datetime64[ns, UTC]