In [1]:
import pandas as pd
import numpy as np
import sqlite3

df = pd.read_csv(r"C:\Users\jayal\Documents\Marketing_Attribution_Project\Cleaned_attribution_data.csv")
print(df.shape)
df.head()

(586737, 6)

,cookie,time,interaction,conversion,conversion_value,channel
0,00000FkCnDfDDf0iC97iC703B,2018-07-03T13:02:11Z,impression,0,0.0,Instagram
1,00000FkCnDfDDf0iC97iC703B,2018-07-17T19:15:07Z,impression,0,0.0,Online Display
2,00000FkCnDfDDf0iC97iC703B,2018-07-24T15:51:46Z,impression,0,0.0,Online Display
3,00000FkCnDfDDf0iC97iC703B,2018-07-29T07:44:51Z,impression,0,0.0,Online Display
4,0000nACkD9nFkBBDECD3ki00E,2018-07-03T09:44:57Z,impression,0,0.0,Paid Search

In [ ]:
#June 22,2026
# Note: Ad spend and clicks data is simulated for analysis purposes
# as actual advertising platform data was not available for this dataset

In [2]:
#Simulated Ad Spend Data 
ad_spend_data = {
    'channel': ['Facebook','Instagram','Online Video','Online Display','Paid Search'],
    'spend': [12000,8000,6000,4000,15000],
    'clicks': [7200,5100,3800,2900,8500]
}
ad_spend = pd.DataFrame(ad_spend_data)
ad_spend.to_csv('ad_spend.csv',index=False)
print("ad_spend.csv created")
ad_spend

ad_spend.csv created

          channel  spend  clicks
0        Facebook  12000    7200
1       Instagram   8000    5100
2    Online Video   6000    3800
3  Online Display   4000    2900
4     Paid Search  15000    8500

In [4]:
import os
print(os.getcwd())

C:\Users\jayal

In [ ]:
#June 25th 2026

In [7]:
import pandas as pd
import numpy as np
import sqlite3

In [8]:
#KPI Calculation
channel_stats = df.groupby('channel').agg(conversions = ('conversion','sum'),
                                         revenue = ('conversion_value','sum')
                                         ).reset_index()

In [9]:
#Merge with ad spend
kpi = pd.merge(channel_stats,ad_spend,on = 'channel',how = 'left')

In [10]:
#KPI calculations
kpi['CPC'] = (kpi['spend']/kpi['clicks']).round(2)
kpi['CAC'] = (kpi['spend']/kpi['conversions']).round(2)
kpi['ROAS'] = (kpi['revenue']/kpi['spend']).round(2)

kpi = kpi.replace([np.inf, -np.inf],0)
print("KPI Calculated!")
kpi

KPI Calculated!

          channel  conversions  revenue  spend  clicks   CPC   CAC  ROAS
0        Facebook         5301  33143.5  12000    7200  1.67  2.26  2.76
1       Instagram         2244  14039.5   8000    5100  1.57  3.57  1.75
2  Online Display         2139  13298.5   4000    2900  1.38  1.87  3.32
3    Online Video         3408  21418.0   6000    3800  1.58  1.76  3.57
4     Paid Search         4547  28331.5  15000    8500  1.76  3.30  1.89